[package]
name = "ton-block-compressor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
zstd = { version = "0.12" }

[dev-dependencies]
criterion = "0.4"
rand = "0.8.4"
pprof = { version = "0.11", features = ["flamegraph"] }

[[bench]]
name = "all"
harness = false
